# Generated by Django 5.1.4 on 2025-04-04 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0002_recipe_recipe_id_recipe_unique_recipe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='picture',
            field=models.URLField(),
        ),
    ]
