# Generated by Django 5.1.4 on 2025-04-04 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0003_alter_recipe_picture'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='picture',
            new_name='picture_url',
        ),
    ]
