# Generated by Django 5.1.4 on 2025-04-04 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0004_rename_picture_recipe_picture_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='amount',
            old_name='amount',
            new_name='title',
        ),
    ]
